version: '3.9'

services:
    react_app:
        container_name: react_app
        image: im-react-app:1.0.0
        build: ../AmusementParkManager.UI/
        ports:
            - 4200:4200
        depends_on:
            - java_api
    java_api:
        container_name: java_api
        image: im-java-api:1.0.0
        build: .
        ports:
            - 8080:8080
        depends_on:
            mysql-db:  
                condition: service_healthy
        environment:
            SPRING_APPLICATION_JSON: '{
                "spring.jpa.show-sql" : "true",
                "spring.datasource.url"  : "jdbc:mysql://mysql-db:3306/apm?createDatabaseIfNotExist=true",
                "spring.datasource.driverClassName" : "com.mysql.jdbc.Driver",
                "spring.datasource.username" : "root",
                "spring.datasource.password" : "root",
                "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
                "spring.jpa.hibernate.ddl-auto" : "update"
            }'
            
    mysql-db:
        container_name: mysql-db
        image: mysql
        ports:
            - 3306:3306
        restart: always
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 20s
            retries: 10
        environment: 
            - MYSQL_ROOT_PASSWORD=root            
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=apm
